### ISSUE TITLE
Maybe reference image height, width should be update?

### ISSUE THREAD

**Issue by xiaojieguo** [JoeHowse/VisualizingTheInvisible#1]
Hi, Joseph
In line 231 of file VisualizingTheInvisible.py, the variable 'reference_image_h', and 'reference_image_w' maybe need to update, because the bgr_reference_image has been resized. Otherwise, the for loop in line 244, the key points and feature calculation won't be the whole reference image, it's just a piece of the image.

**Comment by JoeHowse** [comment]
Thanks, you are correct!  I have now pushed a fix.

**Comment by xiaojieguo** [comment]
I want to thank you, I learned so much from your book.

**Comment by JoeHowse** [comment]
I am happy to hear that!  You are very welcome!
